FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y gcc g++ cmake make pkg-config && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
